### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by mr-git-gud** [mr-git-gud/ohai-app#26]
- [x] Helper function for fetch calls

- [x] Set up Docker

- [x] Set up CI/CD
